plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.jetbrains:annotations:24.1.0'
    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'

    // Dotenv
    implementation 'org.slf4j:slf4j-simple:2.0.16'
    implementation 'io.github.cdimascio:dotenv-java:3.0.0'

    // ClickHouse
    implementation 'com.clickhouse:clickhouse-jdbc:0.6.5'
    implementation 'com.clickhouse:clickhouse-client:0.6.5'
    implementation 'org.apache.httpcomponents.client5:httpclient5:5.3.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'

    // Qdrant
    implementation 'io.qdrant:client:1.13.0'
    implementation 'io.grpc:grpc-netty-shaded:1.75.0'
    implementation 'com.google.guava:guava:33.0.0-jre'
    implementation 'com.google.protobuf:protobuf-java:4.28.2'

    // Redis
    implementation 'redis.clients:jedis:7.1.0'

    // Kafka
    implementation 'org.apache.kafka:kafka-clients:3.9.1'

    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}